### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RomainBrault** [ngoix/OCRF#2]
- [x] Aggarwal & Yu
- [x] OCRF
- [x] RF

**Comment by xchangGt** [comment]
I have downloaded the code and installed library with Conda following the instructions. 
I tested both libraries of Isolation forest in this project (IsolationforestOCRF) and Isolation forest installed in the root environment of Conda (IsolationforestSklearn). 
I found the outputs of method predict() in two packages are different. The output of method predict() of IsolationforestOCRF is an vector with real numbers.  The output of method predict() of IsolationforestSklearn is an vector with binary labels. 
IsolationforestOCRF doesn't support parameter "contamination".
The absolution value of output of method predict() and decision_function() of IsolationforestOCRF are same. Running on the same dataset, however, the outputs of method decision_function() of IsolationforestOCRF and IsolationforestSklearn are quite different. The result of anomaly detection with IsolationforestSklearn is much better.
I try to use the one class random forest in my research. The result of OCRF and IsolationforestOCRF looks similar. Is there any problem with the implement of OCRF and IsolationforestOCRF in this package?
