### ISSUE TITLE
Inconsistent results with scikit-learn

### ISSUE THREAD

**Issue by xchangGt** [ngoix/OCRF#3]
I have downloaded the code and installed the library with Conda following the instructions.
I tested both libraries of Isolation forest in this project (IsolationforestOCRF) and Isolation forest installed in the root environment of Conda (IsolationforestSklearn).
1. I found outputs of the method predict() in the two packages are different. 
   The output of method predict() of IsolationforestOCRF is an vector with real numbers. 
   The output of method predict() of IsolationforestSklearn is an vector with binary labels.
2. The result of anomaly detection with IsolationforestSklearn is much better than IsolationforestOCRF .
3. The results of OCRF and IsolationforestOCRF look similar.
4. The absolute value of output of method predict() and decision_function() of IsolationforestOCRF are 
    same.
5. Running on the same dataset, however, the outputs of method decision_function() of 
    IsolationforestOCRF and IsolationforestSklearn are quite different.
6. IsolationforestOCRF doesn't support parameter "contamination".

Regarding the issues listed above, is there any problem with the implementation of OCRF and IsolationforestOCRF in this package?

**Comment by ngoix** [comment]
Hello,

you should not use the version of isolation forest on the master branch, as we had to modify the cython code for trees (for OneClassRF). 

To reproduce the experiemnts from our paper, the benchmark code for isolation forest is in the branch `benchmark_iforest` . The isolation forest implementation here is not updated, but the only difference with the "new" isolation forest from scikit learn is the fact that the `predict` method is not binary, and the `contamination` parameter is not here - but as this parameter is only used precisely to produce binary labels, it is not used for ROC curves computation anyway.

**Comment by xchangGt** [comment]
Hi Nicolas,
Thanks for the reply. Is the implementation of isolation forest in the branch benchmark_iforest same with the implementation of isolation forest in scikit-learn?
It seems like the isolation forest in scikit-learn adopted the regression decision tree, and OCRF here used classification decision tree. You mentioned that you had to modify the cython code for trees. Have you updated the code here?

**Comment by ngoix** [comment]
The branch `benchmark_iforest` is basically just a clone of scikit-learn 10 months ago, plus some tools used for the benchmarks (such as `one_class_data`) which are shared with the master branch. The tree cython code (which is the same for classification and regression) is unchanged wrt scikit learn.
