### ISSUE TITLE
Question about the OCRFsampling unsupervised method

### ISSUE THREAD

**Issue by mlleberthe** [ngoix/OCRF#5]
Hi,

My issue doesn't point out a specific problem, I just have one question about the OCRF unsupervised ROC and PR results (cf. **bench_ocrf_roc_pr_unsupervised_factorized.png**). 

I presumed that this OCRF method refers to the "OCRFsampling" (Désir et al., 2013).

But I was wondering how these results generated with the **bench_ocrf.py** file, are supposed to be unsupervised since the `fit_predict` fonction needs the `y_train` and `y_test`
(cf line 97 : `scoring = model.fit_predict(X_train, y_train, X_test, y_test)`).

Thank you for your help.

Best regards,

MlleBerthe

**Comment by ngoix** [comment]
Hi,
I think this API it is due to the source code provided by the authors of OCRFsampling. I think `y_train` is yet not used during training. @RomainBrault can you confirm?

**Comment by drougui** [comment]
Hi,
I also think that y_train is never used by
https://github.com/ngoix/OCRF/tree/master/sklearn/ensemble/ocrf_open/ocrf_v0.6
but necessary to make the dataset have the proper structure with arff extension.
https://github.com/ngoix/OCRF/blob/master/sklearn/ensemble/OCRF.py

**Comment by mlleberthe** [comment]
Ok ok, I see.

Thank you for the quick feedback :) :)

**Comment by RomainBrault** [comment]
Confirmed. It's never used.

We also ended up using X_train, y_train, X_test, y_test for
supervised/unsupervised to help automatization of our tests, although as
mentioned above y_train is not used in the unsup context.

2017-09-19 17:20 GMT+02:00 mlleberthe <notifications@github.com>:

**Comment by mlleberthe** [comment]
Ok, thank you all for your answers :) 👍
